# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-01 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='label',
            field=models.CharField(choices=[('functionality', 'Functionality'), ('design', 'Design')], max_length=13),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature')], max_length=7),
        ),
    ]
